notifications:
  email: false

sudo: required

services:
  - docker

install:
  - docker pull quay.io/pypa/manylinux1_x86_64

script:
  - sh manylinux1
  - ls wheelhouse/

before-deploy:
  - rm -rf dist
  - ln -nsf wheelhouse dist
deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: wheelhouse/*.whl
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: __token__
    passowrd: $PYPI_API_KEY
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    index: https://test.pypi.org/legacy/
